'use client';

import type { MandateAgent } from '@/lib/types';

/**
 * V2.3c — the institutional GROUNDING CARD (right rail, AgentPanel sibling): the sourced published
 * mandate with its retrieval date (the reader's freshness signal), the exact computed facts the
 * voice cites with their honesty notes, the not-a-statement disclaimer, and the interview affordance.
 * Everything shown is code-rendered from the artifact — this card IS the "what does it stand on".
 */
export function InstitutionPanel({
  agent,
  onClose,
  onInterview,
}: {
  agent: MandateAgent | null;
  onClose: () => void;
  onInterview?: (agent: MandateAgent) => void;
}) {
  if (!agent) return null;
  const md = agent.mandate;

  return (
    <div style={panel} data-testid="institution-panel">
      <button style={close} onClick={onClose} aria-label="Close">
        ×
      </button>
      <div style={kicker}>INSTITUTIONAL PERSPECTIVE · MANDATE LENS</div>
      <div style={label}>{agent.persona.label}</div>

      <div style={mandateBox} data-testid="institution-mandate">
        <div style={mandateHead}>
          Published mandate —{' '}
          <a style={srcLink} href={md.source} target="_blank" rel="noreferrer">
            source
          </a>{' '}
          · retrieved {md.retrieved}
        </div>
        <div style={mission}>“{md.mission}”</div>
      </div>

      <div style={citesHead}>Facts cited from this run</div>
      {agent.citations.map((c, i) => (
        <div key={i} style={citeBox} data-testid="institution-citation">
          <div style={citeText}>{c.text}</div>
          {(c.notes ?? []).map((n, j) => (
            <div key={j} style={citeNote}>
              {n}.
            </div>
          ))}
        </div>
      ))}

      <div style={disclaimer} data-testid="institution-disclaimer">
        Generated by this tool from the organization’s published mandate and this run’s computed
        facts — not a statement by, from, or on behalf of {md.institution}.
      </div>

      {onInterview && (
        <button
          style={interviewBtn}
          data-testid="interview-open-institution"
          onClick={() => onInterview(agent)}
          title="Ask questions answered from the published mandate + this run's computed facts only."
        >
          {'🎤 Interview · <1¢'}
        </button>
      )}
    </div>
  );
}

const panel: React.CSSProperties = {
  position: 'relative',
  width: '100%',
  padding: '16px 18px',
  borderRadius: 12,
  background: 'rgba(255,255,255,0.97)',
  boxShadow: '0 4px 18px rgba(0,0,0,0.22)',
  borderLeft: '3px solid #3e6b8f',
  pointerEvents: 'auto',
  fontFamily: 'system-ui, sans-serif',
};
const close: React.CSSProperties = {
  position: 'absolute',
  top: 8,
  right: 10,
  border: 'none',
  background: 'transparent',
  fontSize: 20,
  lineHeight: 1,
  color: '#999',
  cursor: 'pointer',
};
const kicker: React.CSSProperties = { fontSize: 10, letterSpacing: 0.6, textTransform: 'uppercase', color: '#3e6b8f' };
const label: React.CSSProperties = { fontSize: 16, fontWeight: 700, color: '#1f2937', margin: '2px 0 10px' };
const mandateBox: React.CSSProperties = { background: '#eef3f7', borderRadius: 8, padding: '8px 10px', marginBottom: 10 };
const mandateHead: React.CSSProperties = { fontSize: 10.5, color: '#4b5f70', marginBottom: 4 };
const srcLink: React.CSSProperties = { color: '#1f4e9c', textDecoration: 'underline' };
const mission: React.CSSProperties = { fontSize: 12, lineHeight: 1.45, color: '#374151', fontStyle: 'italic' };
const citesHead: React.CSSProperties = { fontSize: 10, letterSpacing: 0.5, textTransform: 'uppercase', color: '#9aa0a6', marginBottom: 4 };
const citeBox: React.CSSProperties = { borderLeft: '2px solid #d7dbe0', padding: '2px 0 2px 8px', marginBottom: 8 };
const citeText: React.CSSProperties = { fontSize: 12.5, color: '#1f2937', lineHeight: 1.4, fontVariantNumeric: 'tabular-nums' };
const citeNote: React.CSSProperties = { fontSize: 10.5, color: '#6b7280', fontStyle: 'italic', marginTop: 2 };
const disclaimer: React.CSSProperties = {
  fontSize: 10.5,
  lineHeight: 1.4,
  color: '#8a6d1a',
  background: '#fdf6e3',
  borderRadius: 8,
  padding: '6px 8px',
  marginTop: 4,
};
const interviewBtn: React.CSSProperties = {
  marginTop: 10,
  border: 'none',
  background: '#e8f0fe',
  color: '#1f4e9c',
  borderRadius: 8,
  padding: '6px 10px',
  fontSize: 12,
  fontWeight: 600,
  cursor: 'pointer',
};
