"""V2.5a — the Playwright institutions fixture must BE a real 0.9.0 artifact (the school-zone
regen-pin convention): generated by the real producers (build_multimodal_artifact +
compute_scorecard + institutions.speaking_institutions → compose_citations/compose_reaction →
reactions.build_agent) from the inputs pinned here — these tests fail on any drift, so a
hand-edited fixture-only cosmetic is impossible. It replaces institutions.spec.ts's hand-mocked
mandate agent (whose disclaimer literal had ALREADY drifted from the producer, surviving on a
shared substring).

The change set is the V2.5a SYNERGY shape: a 2-member ALL-WINDOWED DISJOINT composite whose
hand-pinned response_detour side carries the window-coincidence note (via the real
response_probe helper, never re-typed) — one committed fixture exercises the item-1 sentence
(citation notes), the item-3 clause (scorecard scope note), and the institutional rendering in
the real UI. Sim/inferred reaction PROSE is stubbed (production prose is LLM-authored; a
committed fixture necessarily stubs it) — structure still flows through reactions.build_agent,
the single builder.

Regenerate:  python python/tests/test_institutions_fixture.py
             (writes institutions-run.json + institutions-report-section.json)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "python" / "src"))

import trajectory_io  # noqa: E402
from contract_models import Change, Reaction, Window  # noqa: E402

FIXTURE = REPO / "web" / "tests" / "fixtures" / "institutions-run.json"
SECTION_FIXTURE = REPO / "web" / "tests" / "fixtures" / "institutions-report-section.json"
NETWORK = REPO / "web" / "public" / "network.json"

RUN_ID = "institutions-fixture"
SIM_END = 1800.0
WINDOW_A = Window(start_s=300.0, end_s=600.0)     # road_closure
WINDOW_B = Window(start_s=1500.0, end_s=1800.0)   # speed_limit — disjoint from A (gap 600–1500)


def _edges() -> list[dict]:
    """Two deterministic car edges from the canonical network export (real ids + geometry — the
    frontend's networkLookup join resolves overlays; the school-zone _zone_edges idiom)."""
    edges = json.loads(NETWORK.read_text(encoding="utf-8"))["edges"]
    car = [e for e in edges if e["allows"]["car"] and len(e["geometry"]) >= 2]
    return sorted(car, key=lambda e: e["id"])[:2]


def _changes(pair: list[dict]) -> list[Change]:
    a, b = pair
    return [
        Change(type="road_closure", target_edge=a["id"], window=WINDOW_A,
               description=f"Closed {a['id']} from t=300 s to t=600 s"),
        Change(type="speed_limit", target_edge=b["id"], value_mps=8.33, window=WINDOW_B,
               description=f"Reduced max speed on edge {b['id']} to 30 km/h from t=1500 s to t=1800 s"),
    ]


def _detour_side(changes: list[Change]) -> dict:
    """A V2.5b MEMBERS-shape response_detour payload built FROM the real constants — every
    honesty sentence comes from response_probe (never re-typed), so a constant edit regenerates
    here. The capacity gate probes ONLY the road_closure member (the windowed speed_limit fails
    it → probed_members_note owed); the disjoint windows owe the coincidence note (V2.5a)."""
    import response_probe

    wc = response_probe.window_coincidence_note(changes)
    assert wc is not None, "fixture invariant: the change set must owe the coincidence note"
    a = changes[0]  # the road_closure — the only capacity-event member of this change set
    assert a.type == "road_closure" and a.window is not None
    return {
        "framing": response_probe.FRAMING,
        "lower_bound_note": response_probe.LOWER_BOUND_NOTE,
        "end_method_note": response_probe.END_METHOD_NOTE,
        "probed_members_note": response_probe.PROBED_MEMBERS_NOTE,
        "origins_note": ("probe origins are Toronto Fire Services station locations (Toronto Open "
                         "Data, retrieved 2026-07-25); routes are computed from every station and "
                         "do not indicate which station would respond"),
        "window_coincidence_note": wc,
        "modified_edges": sorted({c.target_edge for c in changes}),
        "origins": [
            {"label": "Fire Station 232 (1550 Midland Ave)", "represents": "fire_station",
             "origin_edge": "O1"},
            {"label": "Fire Station 234 (40 Coronation Dr)", "represents": "fire_station",
             "origin_edge": "O2"},
        ],
        "members": [
            {"edge": a.target_edge, "type": "road_closure",
             "window": {"start_s": a.window.start_s, "end_s": a.window.end_s},
             "ends": [
                 {"node": "J1", "label": "east end", "probes": [
                     {"label": "Fire Station 232 (1550 Midland Ave)", "baseline_s": 80.0,
                      "scenario_s": 90.2, "added_s": 10.2},
                     {"label": "Fire Station 234 (40 Coronation Dr)", "baseline_s": 120.0,
                      "scenario_s": 149.1, "added_s": 29.1}]},
                 {"node": "J2", "label": "west end", "probes": [
                     {"label": "Fire Station 232 (1550 Midland Ave)", "baseline_s": 82.0,
                      "scenario_s": None, "added_s": None,
                      "note": response_probe.END_UNREACHABLE_NOTE},
                     {"label": "Fire Station 234 (40 Coronation Dr)", "baseline_s": 118.0,
                      "scenario_s": 124.0, "added_s": 6.0}]},
             ]},
        ],
    }


def _side(changes: list[Change]) -> dict:
    # response_detour only — TFS speaks; zero diversions keep ops silent (presence is not
    # standing) and no zone_facts keeps TDSB silent. One institutional voice, focused fixture.
    return {"reroute": {"cars_rerouted": 0, "cars_matched": 300},
            "response_detour": _detour_side(changes)}


def _records(pair: list[dict]) -> dict:
    recs: dict = {}
    for i, e in enumerate(pair):
        pts = e["geometry"]
        n = len(pts)
        recs[f"veh{i}"] = {"type": "car", "path": pts,
                           "timestamps": [round(j * SIM_END / max(n - 1, 1), 1) for j in range(n)],
                           "speeds": [8.0] * n}
    return recs


def _buckets() -> dict:
    return {m: {"counts": {"total_demand": 10}, "outcomes": [{"delta_seconds": d} for d in (0.5, 1.5, 2.0)]}
            for m in ("car", "bicycle", "pedestrian")}


def _bbox(pair: list[dict]) -> list[float]:
    lons = [p[0] for e in pair for p in e["geometry"]]
    lats = [p[1] for e in pair for p in e["geometry"]]
    return [min(lons) - 0.01, min(lats) - 0.01, max(lons) + 0.01, max(lats) + 0.01]


def _voice_records(side: dict) -> list[tuple[dict, Reaction]]:
    """Sampler-shaped records + deterministic reactions, in the sampler's order (sim, inferred,
    mandate LAST — index stability). The mandate pair replicates reactions._guarded's mandate
    branch line-for-line: compose_citations stamped onto the record, compose_reaction as prose."""
    import institutions

    sim_rec = {"grounding": "sim", "mode": "car",
               "persona": {"id": "time_pressed", "label": "Time-pressed commuter"},
               "vehicle_id": "veh0", "trigger_t": 450.0,
               "outcome": {"baseline_duration": 600.0, "scenario_duration": 645.0,
                           "delta_seconds": 45.0, "baseline_timeloss": 30.0,
                           "scenario_timeloss": 75.0}}
    sim_reaction = Reaction(
        comment="My usual drive felt longer while the closure was up — tight mornings got tighter.",
        sentiment=-0.4, stance="opposed")
    inf_rec = {"grounding": "inferred", "mode": "inferred",
               "persona": {"id": "longtime_resident", "label": "Long-time corridor resident"}}
    inf_reaction = Reaction(
        comment="Life on the corridor shifts when a stretch closes, even briefly — folks notice "
                "the detour traffic on side streets.",
        sentiment=-0.1, stance="neutral")

    out: list[tuple[dict, Reaction]] = [(sim_rec, sim_reaction), (inf_rec, inf_reaction)]
    for entry, facts in institutions.speaking_institutions(side):
        rec = {"grounding": "mandate", "mode": "mandate",
               "persona": {"id": entry["id"], "label": entry["label"]},
               "mandate": dict(entry["mandate"]), "mission_clause": entry["mission_clause"],
               "cites": list(entry.get("cites", [])), "facts": facts}
        citations = institutions.compose_citations(entry, facts)
        rec["citations"] = citations
        out.append((rec, institutions.compose_reaction(entry, citations)))
    return out


def _build():
    import reactions
    import scenario_harness as sh
    import scorecard

    pair = _edges()
    changes = _changes(pair)
    side = _side(changes)
    art = sh.build_multimodal_artifact(
        _records(pair), [], run_id=RUN_ID, baseline_run_id="institutions-fixture-baseline",
        changes=changes, tags=None, target_lane=None,
        bbox=_bbox(pair), sim_end=SIM_END, step=1.0)
    art.scorecard = scorecard.compute_scorecard(
        _buckets(), [], [], [c.model_dump(exclude_none=True) for c in changes])
    art.agents = [reactions.build_agent(rec, reaction) for rec, reaction in _voice_records(side)]
    return art


def _institutional_facts(art) -> dict:
    """The report.gather_facts institutional sub-dict, replicated shape-for-shape (report.py) —
    the companion section fixture is build_institutional_section over exactly this."""
    return {
        "schema_version": art.schema_version,
        "institutional": [
            {"id": a.persona.id, "label": a.persona.label,
             "mandate": a.mandate.model_dump(),
             "citations": [c.model_dump(exclude_none=True) for c in (a.citations or [])],
             "comment": a.reaction.comment}
            for a in art.agents if a.grounding == "mandate"
        ],
    }


def test_fixture_is_a_valid_disjoint_mandate_artifact() -> None:
    assert FIXTURE.is_file(), f"committed institutions fixture missing: {FIXTURE} — regenerate: python {__file__}"
    raw = json.loads(FIXTURE.read_text(encoding="utf-8"))
    trajectory_io.validate_artifact(raw)
    trajectory_io.audit_version_gate(raw)
    assert raw["schema_version"] == "0.9.0"
    scen = raw["meta"]["scenario"]
    assert len(scen["changes"]) == 2 and "tags" not in scen
    assert [c["type"] for c in scen["changes"]] == ["road_closure", "speed_limit"]
    assert scen["changes"][0]["window"] == {"start_s": 300.0, "end_s": 600.0}
    assert scen["changes"][1]["window"] == {"start_s": 1500.0, "end_s": 1800.0}
    groundings = [a["grounding"] for a in raw["agents"]]
    assert groundings == ["sim", "inferred", "mandate"]  # mandate appended LAST (index stability)
    assert raw["agents"][2]["persona"]["id"] == "tfs"


def test_fixture_equals_real_producer_output() -> None:
    art = trajectory_io.load_artifact(FIXTURE)
    expected = _build()
    assert art.meta.scenario.model_dump(exclude_none=True) == \
        expected.meta.scenario.model_dump(exclude_none=True), (
            "the fixture's scenario drifted from the real producer output — regenerate, never hand-edit")
    assert art.scorecard.model_dump(exclude_none=True) == \
        expected.scorecard.model_dump(exclude_none=True)
    # agents too — every reaction here is deterministic (stubbed sim/inferred prose is pinned
    # above; the mandate voice is composed by the real deterministic chain)
    assert [a.model_dump(exclude_none=True) for a in art.agents] == \
        [a.model_dump(exclude_none=True) for a in expected.agents]


def test_fixture_mandate_is_roster_verbatim_and_notes_ride() -> None:
    import institutions
    import response_probe

    art = trajectory_io.load_artifact(FIXTURE)
    tfs = next(a for a in art.agents if a.grounding == "mandate")
    roster = next(e for e in institutions.load_roster() if e["id"] == "tfs")
    assert tfs.mandate.mission == roster["mandate"]["mission"]  # byte-identical, never reworded
    notes = tfs.citations[0].notes or []
    assert response_probe.FRAMING in notes
    assert response_probe.LOWER_BOUND_NOTE in notes
    assert response_probe.WINDOW_COINCIDENCE_NOTE in notes  # the V2.5a item-1 sentence rides
    assert response_probe.END_METHOD_NOTE in notes          # V2.5b: the end-method sentence rides
    assert response_probe.PROBED_MEMBERS_NOTE in notes      # V2.5b: the gate gap is named
    assert any("do not indicate which station would respond" in n for n in notes)
    # the aggregated members citation (V2.5b): per-end rollup, count-not-name for the
    # one-end-cut-off station, no legacy number-bearing metric phrase
    assert "east end worst +29.1 s" in tfs.citations[0].text
    assert "west end worst of the reachable +6 s (1 of 2 unreachable)" in tfs.citations[0].text
    assert "s added response-route time" not in tfs.citations[0].text


def test_fixture_change_set_owes_both_new_disclosures() -> None:
    """The synergy invariant: this ONE fixture exercises the item-1 note AND the item-3 clause."""
    import report
    import response_probe
    import zone_lens

    art = trajectory_io.load_artifact(FIXTURE)
    changes = art.meta.scenario.changes
    assert response_probe.window_coincidence_note(changes) == response_probe.WINDOW_COINCIDENCE_NOTE
    assert zone_lens.windows_disjoint(changes) is True
    disclosure = report.build_scope_disclosure(changes, art.meta.sim_end,
                                               art.meta.demand_profile or "synthetic_demo")
    assert zone_lens.DISJOINT_SPAN_CLAUSE in disclosure


def test_fixture_edges_exist_in_the_network_export() -> None:
    net_ids = {e["id"] for e in json.loads(NETWORK.read_text(encoding="utf-8"))["edges"]}
    art = trajectory_io.load_artifact(FIXTURE)
    for c in art.meta.scenario.changes:
        assert c.target_edge in net_ids


def test_companion_section_equals_recompute() -> None:
    """The report-side fixture (spliced into institutions.spec.ts's report mock) must equal
    build_institutional_section over the fixture artifact — this is what killed the spec's
    drifted hand-authored disclaimer literal."""
    import report

    assert SECTION_FIXTURE.is_file(), f"companion missing: {SECTION_FIXTURE} — regenerate: python {__file__}"
    committed = json.loads(SECTION_FIXTURE.read_text(encoding="utf-8"))
    art = trajectory_io.load_artifact(FIXTURE)
    expected = report.build_institutional_section(_institutional_facts(art))
    assert committed == expected, "companion section drifted — regenerate, never hand-edit"
    assert committed["disclaimer"] == report.INSTITUTIONAL_DISCLAIMER


if __name__ == "__main__":
    import report

    artifact = _build()
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    trajectory_io.dump_artifact(artifact, path=FIXTURE)
    section = report.build_institutional_section(_institutional_facts(artifact))
    SECTION_FIXTURE.write_text(json.dumps(section, indent=2, ensure_ascii=False) + "\n",
                               encoding="utf-8")
    print(f"wrote {FIXTURE}")
    print(f"wrote {SECTION_FIXTURE}")
