"""V2.2d — the Playwright school-zone fixture must BE a real artifact (seeds-run convention).

school-zone.spec.ts renders web/tests/fixtures/school-zone-run.json through the normal
loadArtifact -> MapView path. The fixture is GENERATED by the real producers
(build_multimodal_artifact + compute_scorecard) from the inputs pinned here — these tests fail on
any drift, so a hand-edited fixture-only cosmetic is impossible.

Regenerate:  python python/tests/test_school_zone_fixture.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "python" / "src"))

import trajectory_io  # noqa: E402
from contract_models import Change, Window  # noqa: E402

FIXTURE = REPO / "web" / "tests" / "fixtures" / "school-zone-run.json"
NETWORK = REPO / "web" / "public" / "network.json"

RUN_ID = "school-zone-fixture"
WINDOW = Window(start_s=600.0, end_s=1200.0)
SPEED_MPS = 8.33  # 30 km/h
SIM_END = 1800.0


def _zone_edges() -> list[dict]:
    """Three deterministic car edges from the canonical network export (real ids + geometry, so the
    frontend's networkLookup join resolves every member's overlay path)."""
    edges = json.loads(NETWORK.read_text(encoding="utf-8"))["edges"]
    car = [e for e in edges if e["allows"]["car"] and len(e["geometry"]) >= 2]
    return sorted(car, key=lambda e: e["id"])[:3]


def _changes(zone: list[dict]) -> list[Change]:
    return [Change(type="speed_limit", target_edge=e["id"], value_mps=SPEED_MPS, window=WINDOW,
                   description=f"Reduced max speed on edge {e['id']} to 30 km/h from t=600 s to t=1200 s")
            for e in zone]


def _records(zone: list[dict]) -> dict:
    """Three cars driving the zone edges' real geometry across the sim (timestamps span the window
    so playback scrubbing crosses before/inside/after)."""
    recs: dict = {}
    for i, e in enumerate(zone):
        pts = e["geometry"]
        n = len(pts)
        recs[f"veh{i}"] = {"type": "car", "path": pts,
                           "timestamps": [round(j * SIM_END / max(n - 1, 1), 1) for j in range(n)],
                           "speeds": [8.0] * n}
    return recs


def _buckets() -> dict:
    return {m: {"counts": {"total_demand": 10}, "outcomes": [{"delta_seconds": d} for d in (0.5, 1.5, 2.0)]}
            for m in ("car", "bicycle", "pedestrian")}


def _bbox(zone: list[dict]) -> list[float]:
    lons = [p[0] for e in zone for p in e["geometry"]]
    lats = [p[1] for e in zone for p in e["geometry"]]
    return [min(lons) - 0.01, min(lats) - 0.01, max(lons) + 0.01, max(lats) + 0.01]


def _build():
    import scenario_harness as sh
    import scorecard

    zone = _zone_edges()
    changes = _changes(zone)
    art = sh.build_multimodal_artifact(
        _records(zone), [], run_id=RUN_ID, baseline_run_id="school-zone-fixture-baseline",
        changes=changes, tags=["school_zone"], target_lane=None,
        bbox=_bbox(zone), sim_end=SIM_END, step=1.0)
    art.scorecard = scorecard.compute_scorecard(
        _buckets(), [], [], [c.model_dump(exclude_none=True) for c in changes])
    return art


def test_fixture_is_a_valid_tagged_composite() -> None:
    assert FIXTURE.is_file(), f"committed school-zone fixture missing: {FIXTURE} — regenerate: python {__file__}"
    raw = json.loads(FIXTURE.read_text(encoding="utf-8"))
    trajectory_io.validate_artifact(raw)
    trajectory_io.audit_version_gate(raw)
    assert raw["schema_version"] == "0.8.0"
    scen = raw["meta"]["scenario"]
    assert len(scen["changes"]) == 3 and scen["tags"] == ["school_zone"]
    assert all(c["type"] == "speed_limit" for c in scen["changes"])
    assert all(c["window"] == {"start_s": 600.0, "end_s": 1200.0} for c in scen["changes"])


def test_fixture_equals_real_producer_output() -> None:
    art = trajectory_io.load_artifact(FIXTURE)
    expected = _build()
    assert art.meta.scenario.model_dump(exclude_none=True) == \
        expected.meta.scenario.model_dump(exclude_none=True), (
            "the fixture's scenario drifted from the real producer output — regenerate, never hand-edit")
    assert art.scorecard.model_dump(exclude_none=True) == \
        expected.scorecard.model_dump(exclude_none=True)
    # the school-zone access truth: NO access heuristic for speed_limit — absent, like a single run
    assert all(g.access_delta is None for g in art.scorecard.groups)


def test_fixture_edges_exist_in_the_network_export() -> None:
    # the spec's overlay/tint assertions depend on the networkLookup geometry join resolving
    net_ids = {e["id"] for e in json.loads(NETWORK.read_text(encoding="utf-8"))["edges"]}
    art = trajectory_io.load_artifact(FIXTURE)
    for c in art.meta.scenario.changes:
        assert c.target_edge in net_ids


if __name__ == "__main__":
    artifact = _build()
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    trajectory_io.dump_artifact(artifact, path=FIXTURE)
    print(f"wrote {FIXTURE}")
